// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20211220165311_samp")]
    partial class samp

    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Database.Item", b =>
                {
                    b.Property<int>("ObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int?>("DetailsImageId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("H")
                        .HasColumnType("REAL");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<float>("W")
                        .HasColumnType("REAL");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("ObjectId");

                    b.HasIndex("DetailsImageId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Database.ItemDetails", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.HasKey("ImageId");

                    b.ToTable("ItemDetails");
                });

            modelBuilder.Entity("Database.Item", b =>
                {
                    b.HasOne("Database.ItemDetails", "Details")
                        .WithMany()
                        .HasForeignKey("DetailsImageId");

                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
